using InventoryApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace InventoryApp.Controllers
{
    // This controller exposes the AI inventory analysis as a REST API.
    // The frontend can consume this endpoint (dashboard)
    [ApiController]
    [Route("api/[controller]")]
    public class AIController : ControllerBase
    {
        // AI service responsible for reading inventory data
        // and generating the AI analysis.
        private readonly IAIService _aiService;

        public AIController(IAIService aiService)
        {
            _aiService = aiService;
        }

        // GET: /api/ai/inventory-analysis
        //
        // Returns the complete inventory analysis generated by AI.
        //
        // Example:
        // GET https://localhost:PORT/api/ai/inventory-analysis
        [HttpGet("inventory-analysis")]
        public async Task<IActionResult> AnalyzeInventory()
        {
            try
            {
                // Call the AI service.
                // The service handles:
                // 1. Reading products from the database.
                // 2. Calculating stock status.
                // 3. Sending the inventory to Gemini.
                // 4. Validating Gemini's JSON response.
                var result = await _aiService.AnalyzeInventoryAsync();

                // Make sure the service returned something.
                if (string.IsNullOrWhiteSpace(result))
                {
                    return StatusCode(500, new
                    {
                        success = false,
                        error = "AI service returned an empty response."
                    });
                }

                // Parse the returned JSON so that the API returns
                // a real JSON object instead of a JSON string.
                using var jsonDocument = JsonDocument.Parse(result);

                var root = jsonDocument.RootElement;

                // Read the "success" property if it exists.
                if (root.TryGetProperty("success", out var successProperty))
                {
                    var success = successProperty.GetBoolean();

                    // If the AI service reports an error,
                    // return it as an appropriate HTTP response.
                    if (!success)
                    {
                        return StatusCode(500, root.Clone());
                    }
                }

                // Return the complete JSON object directly.
                return Ok(root.Clone());
            }
            catch (JsonException)
            {
                // Returned data was not valid JSON.
                return StatusCode(500, new
                {
                    success = false,
                    error = "The AI service returned invalid JSON."
                });
            }
            catch (Exception ex)
            {
                // Handle unexpected server-side errors.
                return StatusCode(500, new
                {
                    success = false,
                    error = "An unexpected error occurred while analyzing inventory.",
                    details = ex.Message
                });
            }
        }
    }
}